#!/usr/bin/env bash

# -----------------------------------------------------------------------------
# This script was automatically generated by installscript.
#
# This file is produced from a YAML configuration and is intended to automate
# the installation of software packages and dependencies for Linux systems.
#
# Any manual changes to this file will be lost if it is regenerated.
# To modify the installation process, edit the YAML config and regenerate.
#
# For more information, visit: https://github.com/RaniAgus/installscript
# -----------------------------------------------------------------------------

set -e

sudo apt-get install -y flatpak

flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo

flatpak install -y flathub org.kde.kdenlive

flatpak install -y flathub net.pcsx2.PCSX2

flatpak install -y flathub com.github.jeromerobert.pdfarranger

flatpak install -y flathub com.obsproject.Studio

flatpak install -y flathub com.discordapp.Discord

flatpak install -y flathub com.github.maoschanz.drawing
