#!/usr/bin/env bash

# -----------------------------------------------------------------------------
# This script was automatically generated by installscript.
#
# This file is produced from a YAML configuration and is intended to automate
# the installation of software packages and dependencies for Linux systems.
#
# Any manual changes to this file will be lost if it is regenerated.
# To modify the installation process, edit the YAML config and regenerate.
#
# For more information, visit: https://github.com/RaniAgus/installscript
# -----------------------------------------------------------------------------

set -e

TMP_DIR=$(mktemp -d)
git clone https://github.com/mumuki/cspec.git $TMP_DIR
(
  cd $TMP_DIR
  make
  sudo make install
)
rm -rf $TMP_DIR

TMP_DIR=$(mktemp -d)
git clone https://github.com/sisoputnfrba/so-commons-library.git $TMP_DIR
(
  cd $TMP_DIR
  make
  sudo make install
)
rm -rf $TMP_DIR
