#!/usr/bin/env bash

# -----------------------------------------------------------------------------
# This script was automatically generated by installscript.
#
# This file is produced from a YAML configuration and is intended to automate
# the installation of software packages and dependencies for Linux systems.
#
# Any manual changes to this file will be lost if it is regenerated.
# To modify the installation process, edit the YAML config and regenerate.
#
# For more information, visit: https://github.com/RaniAgus/installscript
# -----------------------------------------------------------------------------

set -e

sudo apt-get install -y "fuse" "libfuse2"

mkdir -p "$(dirname "$HOME/.local/bin/DuckStation.AppImage")"
curl -fsSL "https://github.com/stenzek/duckstation/releases/download/latest/DuckStation-x64.AppImage" -o "$HOME/.local/bin/DuckStation.AppImage" > /dev/null
chmod +x "$HOME/.local/bin/DuckStation.AppImage"

mkdir -p "$(dirname "$HOME/.local/share/applications/DuckStation.desktop)"
tee "$HOME/.local/share/applications/DuckStation.desktop" <<'EOF'
[Desktop Entry]
Name=DuckStation
StartupNotify=true
Type=Application
Terminal=false
Categories=Game;Emulator;
Icon=org.duckstation.DuckStation
Exec=$HOME/.local/bin/DuckStation.AppImage
EOF

(
  TMP_DIR=$(mktemp -d)
  cd "$TMP_DIR" || exit
  "$HOME/.local/bin/DuckStation.AppImage" --appimage-extract
  cp -rv squashfs-root/usr/share/icons/hicolor/* "$HOME/.local/share/icons/hicolor/" 2>/dev/null || true
  rm -rf "$TMP_DIR"
)
