#!/usr/bin/env bash

# -----------------------------------------------------------------------------
# This script was automatically generated by installscript.
#
# This file is produced from a YAML configuration and is intended to automate
# the installation of software packages and dependencies for Linux systems.
#
# Any manual changes to this file will be lost if it is regenerated.
# To modify the installation process, edit the YAML config and regenerate.
#
# For more information, visit: https://github.com/RaniAgus/installscript
# -----------------------------------------------------------------------------

set -e

sudo dnf install -y dnf5-plugins

# TODO: Add installation command for package: dnf-automatic

sudo dnf install -y kernel kernel-core kernel-modules kernel-modules-core kernel-modules-extra kernel-tools kernel-tools-libs kernel-headers kernel-devel

wget -q https://www.virtualbox.org/download/oracle_vbox_2016.asc -O- | sudo rpm --import -

sudo dnf install -y VirtualBox-7.2
