#!/usr/bin/env bash

# -----------------------------------------------------------------------------
# This script was automatically generated by installscript.
#
# This file is produced from a YAML configuration and is intended to automate
# the installation of software packages and dependencies for Linux systems.
#
# Any manual changes to this file will be lost if it is regenerated.
# To modify the installation process, edit the YAML config and regenerate.
#
# For more information, visit: https://github.com/RaniAgus/installscript
# -----------------------------------------------------------------------------

set -e

sudo dnf install -y python3-pip

sudo dnf install -y make cmake gcc gcc-c++

sudo dnf install -y python3-wheel zlib-devel

pip install -U kazam

printf "%s\n" "[Desktop Entry]" "Name=Kazam" "Comment=Screen recording tool" "Exec=kazam" "Icon=kazam" "Terminal=false" "Type=Application" "Categories=AudioVideo;Recorder;" "StartupNotify=true" | tee ~/.local/share/applications/kazam.desktop

pip install -U yt-dlp[default]
